CC=gcc

# all: gps_to_ang 
all: hello

all: main

main: main.cpp
	$(CC) -o main main.cpp

# gps_to_ang: gps_to_ang.cpp
# 	$(CC) -o map gps_to_ang.cpp

# hello: hello.cpp
# 	$(CC) -o hello hello.cpp

# test: test.cpp
# 	$(CC) -c test.cpp -o test.o

clean: 
	rm gps_to_ang test.o